set positional-arguments

contract := `cat neardev/dev-account`



build:
    cargo build --target wasm32-unknown-unknown --release && cp target/wasm32-unknown-unknown/release/pseudorandom.wasm ./out/main.wasm

deploy: build
    near dev-deploy

deploy-force: build
    near dev-deploy --force

random_seed:
    near view {{contract}} random_seed

random_int:
    near view {{contract}} random_int

random_by_timestamp_and_block max:
    near view {{contract}} random_by_timestamp_and_block '{"max": 10}'


test:
    cargo test -- --nocapture
