set positional-arguments

contract := `cat neardev/dev-account`



build-contract:
    cargo build --target wasm32-unknown-unknown --release && cp target/wasm32-unknown-unknown/release/counter.wasm ./out/main.wasm

deploy: build-contract
    near dev-deploy

deploy-force:
    near dev-deploy --force

value:
    near view {{contract}} value

history:
    near view {{contract}} history

add value:
    near call {{contract}} action --args '{"operation": "add", "param": '$1'}' --accountId {{contract}}

sub value:
    near call {{contract}} action '{"operation": "sub", "param": '$1'}' --accountId {{contract}}

reset:
    near call {{contract}} reset '{}' --deposit 0.1 --accountId {{contract}}
