set positional-arguments

contract := `cat neardev/dev-account`



build:
    cargo build --target wasm32-unknown-unknown --release && cp target/wasm32-unknown-unknown/release/nft.wasm ./out/main.wasm

deploy: build
    near dev-deploy

deploy-force: build
    near dev-deploy --force

init:
    near call {{contract}} new '{"owner_id": "'{{contract}}'", "money_wallet": "maxblock.testnet", "name": "ZZZ Token", "symbol": "ZZZ", "price": "100000000000000000000000"}' --accountId {{contract}}

meta:
    near view {{contract}} nft_metadata

mint_1:
    near call {{contract}} mint_token '{"token_id": "1", "token_metadata": { "title": "title 1", "description": "bla bla 1", "copies": 1}}' --accountId {{contract}} --deposit 0.00597

mint_2:
    near call {{contract}} mint_token '{"token_id": "2", "token_metadata": { "title": "title 2", "description": "bla bla 2", "copies": 1}}' --accountId {{contract}} --deposit 0.00597

token_1:
    near view {{contract}} nft_token '{"token_id": "1"}'

token_2:
    near view {{contract}} nft_token '{"token_id": "2"}'

buy_1:
    near call {{contract}} buy_token '{"token_id": "1"}' --accountId t1.maxblock.testnet --deposit 0.11
